project:
    title: "phpx"
    subtitle: "mixins and metaprogramming for PHP"
    main_nav:
        - ["Overview", "index.html"]
        - ["Usage", "usage.html"]
        - ["Examples", "examples.html"]
