<pre><b>SOMEWHAT CONTRIVED TEST SCENARIO</b><br /><br /><?php
require '../boot.php';

set_include_path(dirname(__FILE__) . '/classes');

class AddressableMacro {
    public function apply($class) {
        $class->attr_accessor('name');
        $class->attr_accessor('address_1');
        $class->attr_accessor('address_2');
        $class->attr_accessor('city');
        $class->attr_accessor('postcode');
        $class->attr_accessor('country');
        $class->mixin('AddressHelper');
    }
}

// Force compiler to load for test purposes
phpx\Stream::load_phpx();
phpx\register_macro('addressable', 'AddressableMacro');

$customer = new Customer;
$customer->set_name('Joe Bloggs');
$customer->set_address_1('100 Puddle Lane');
$customer->set_city('Glasgow');
$customer->set_postcode('G1');
$customer->set_country('UK');

echo "Addressable fields exist and are set:\n";
var_dump($customer);

echo "\nAddressHelper mixed in:\n";
var_dump($customer->is_domestic());

echo "\nSQL generated by static mixin:\n";
echo Customer::sql_for_find_by_id(10);

echo "\n\nStatus setter is overwritten:\n";
$customer->set_status('active');
echo $customer->get_status();

echo "\n\nPattern matching status checker:\n";
echo "active: " . ($customer->is_active() ? 'yes' : 'no');
echo "\ndisabled: " . ($customer->is_disabled() ? 'yes' : 'no');
echo "\nbanned: " . ($customer->is_banned() ? 'yes' : 'no');

echo "\n\nShipping delegation:\n";
$customer->ship();

?></pre>